version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      #alteração porta 9100 (verificar env)
      - "9100:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: bitcenter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "12345"
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
